version: "3.8"
services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 20

  emitron:
    build: .
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - CHANNEL_PREFIX=emitron
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  redis-data:
